firstSTL : firstSTL.o
	g++ ../build/firstSTL.o -o ../build/firstSTL

firstSTL.o : firstSTL.cpp
	g++ -c firstSTL.cpp -o ../build/firstSTL.o

build :
	mkdir ../build/

clean :
	rm ../build/firstSTL.o -o ../build/firstSTL