deviceSearcher : deviceSearcher.o
	gcc  ../build/deviceSearcher.o -o ../build/deviceSearcher

deviceSearcher.o : deviceSearcher.c
	gcc -c deviceSearcher.c -o ../build/deviceSearcher.o

build :
	mkdir ../build/

clean :
	#rm ../build/deviceSearcher.o ../build/deviceSearcher
	rm -rf ../build