deviceSearcher : deviceSearcher.o
	gcc deviceSearcher.o -o deviceSearcher

deviceSearcher.o : deviceSearcher.c
	gcc -c deviceSearcher.c -o deviceSearcher.o

clean :
	rm deviceSearcher.o deviceSearcher
